# Generated by Django 5.0.2 on 2024-04-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='date_posted',
            field=models.DateTimeField(),
        ),
    ]
