# Generated by Django 5.0.2 on 2024-04-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytag',
            name='tag',
            field=models.CharField(choices=[('Furniture', 'Furniture'), ('Appliances', 'Appliances'), ('Textbooks', 'Textbooks'), ('School supplies', 'School supplies'), ('Clothing', 'Clothing'), ('Game tickets', 'Game tickets'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='qualitytag',
            name='tag',
            field=models.CharField(choices=[('Like New', 'Like New'), ('Good', 'Good'), ('Acceptable', 'Acceptable')], max_length=100),
        ),
    ]
