# Generated by Django 5.0.2 on 2024-03-29 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorytag',
            options={'ordering': ('tag',), 'verbose_name_plural': 'CategoryTag'},
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='productinfo',
            name='product_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productlisting',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app2.productinfo'),
        ),
    ]
