# Generated by Django 5.0.2 on 2024-04-06 23:40

from django.db import migrations

def create_initial_tags(apps, schema_editor):
    QualityTag = apps.get_model('app2', 'QualityTag')
    CategoryTag = apps.get_model('app2', 'CategoryTag')

    # Create QualityTags
    QualityTag.objects.bulk_create([
        QualityTag(tag='Like New'),
        QualityTag(tag='Good'),
        QualityTag(tag='Acceptable'),
    ])

    # Create CategoryTags
    CategoryTag.objects.bulk_create([
        CategoryTag(tag='Furniture'),
        CategoryTag(tag='Appliances'),
        CategoryTag(tag='Textbooks'),
        CategoryTag(tag='School supplies'),
        CategoryTag(tag='Clothing'),
        CategoryTag(tag='Game tickets'),
        CategoryTag(tag='Other'),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_alter_productinfo_date_posted'),
    ]

    operations = [
        migrations.RunPython(create_initial_tags),
    ]
