# Generated by Django 5.0.2 on 2024-03-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_alter_productinfo_category_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
