# Generated by Django 5.0.2 on 2024-04-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_alter_categorytag_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='previous_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
