# Generated by Django 5.0.2 on 2024-03-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_productinfo_image_productinfo_is_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='product_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
