# Generated by Django 5.0.2 on 2024-04-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_alter_productinfo_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytag',
            name='tag',
            field=models.CharField(choices=[('Furniture', 'Furniture'), ('Appliances', 'Appliances'), ('Textbooks', 'Textbooks'), ('School supplies', 'School supplies'), ('Clothing', 'Clothing'), ('Game tickets', 'Game tickets'), ('Other', 'Other')], max_length=100),
        ),
    ]
