# Generated by Django 5.0.2 on 2024-04-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_sales_previous_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='price_changed',
            field=models.BooleanField(default=False),
        ),
    ]
