# Generated by Django 5.0.2 on 2024-04-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0008_productinfo_price_changed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='previous_price',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='user',
        ),
    ]
