# Generated by Django 5.0.2 on 2024-03-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
