# Generated by Django 5.0.2 on 2024-04-18 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_profile_average_rating_sellerrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerrating',
            name='seller_email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
