# Generated by Django 5.0.2 on 2024-04-18 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_profile_notifications'),
        ('app', '0008_sellerrating_seller_email'),
    ]

    operations = [
    ]
