# Generated by Django 5.0.2 on 2024-04-19 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge_20240418_0106'),
        ('app', '0009_merge_20240418_1731'),
    ]

    operations = [
    ]
