# Generated by Django 5.0.2 on 2024-04-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_merge_20240418_2249'),
        ('app', '0010_merge_20240419_0024'),
    ]

    operations = [
    ]
